In [1]:
import tensorflow as tf

In [2]:
string = tf.Variable("this is a string", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

In [3]:
print(string)
print(number)
print(floating)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is a string'>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=324>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.566999912261963>


In [4]:
rank1 = tf.Variable(["asqar"], tf.string)
rank2= tf.Variable([['asqar', 'raqsa'], ['mohamad', 'dammahom']], tf.string)

In [5]:
print(rank1,"\n",rank2)

<tf.Variable 'Variable:0' shape=(1,) dtype=string, numpy=array([b'asqar'], dtype=object)> 
 <tf.Variable 'Variable:0' shape=(2, 2) dtype=string, numpy=
array([[b'asqar', b'raqsa'],
       [b'mohamad', b'dammahom']], dtype=object)>


In [6]:
tf.rank(rank2)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [7]:
rank2.shape

TensorShape([2, 2])

In [8]:
tf1 = tf.ones([1,2,3])
tf2 = tf.reshape(tf1, [2,3,1])
tf3 = tf.reshape(tf1, [3,-1])
print(tf1,"\n",tf2,"\n",tf3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32) 
 tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32) 
 tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [9]:
metrics = [[1,2,3,4,5],
           [6,7,8,9,10],
           [11,12,13,14,15],
           [16,17,18,19,20]]
tensor = tf.Variable(metrics,dtype=tf.int32)

In [10]:
print(tf.rank(tensor))
##(row, col)
print(tensor[0,2]) #select element from the one row
print(tensor[0]) #select first row
print(tensor[:,0]) #select first column
print(tensor[1::2]) #select second and fourth row
print(tensor[1:3, 0]) #select col1 in row2 and 3

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor([ 1  6 11 16], shape=(4,), dtype=int32)
tf.Tensor(
[[ 6  7  8  9 10]
 [16 17 18 19 20]], shape=(2, 5), dtype=int32)
tf.Tensor([ 6 11], shape=(2,), dtype=int32)
